enum MimeTypes {
  ApplicationJson = 'application/json',
  ApplicationXml = 'application/xml',
  ApplicationOctetStream =  'application/octet-stream',
  ApplicationRtf = 'application/rtf',
  ApplicationOpenXmlDocument = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ApplicationOpenXmlSpreadsheet = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  ApplicationOpenXmlPresentation = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  ApplicationMsWord = 'application/msword',
  ApplicationMsExcel = 'application/vnd.ms-excel',
  ApplicationPpt = 'application/vnd.ms-powerpoint',
  ImageJpeg = 'image/jpeg',
  ImageJpg = 'image/jpg',
  ImagePng = 'image/png',
  ImageGig =  'image/gif',
  ImageBmp = 'image/bmp',
  ImageTiff = 'image/tiff',
  TextJson = 'text/json',
  TextXml ='text/xml'
}
