export interface Contact {
    TableRight: FieldRightOrTableRight;
    FieldProperties: FieldProperties;
    ContactId: number;
    Name: string;
    Department: string;
    OrgNr: string;
    Number1: string;
    Number2: string;
    UpdatedDate: string;
    CreatedDate: string;
    Emails?: (EmailsEntityOrUrlsEntityOrPhonesEntity)[] | null;
    Interests?: (InterestsEntity)[] | null;
    Urls?: (EmailsEntityOrUrlsEntityOrPhonesEntity)[] | null;
    Phones?: (EmailsEntityOrUrlsEntityOrPhonesEntity)[] | null;
    Faxes?: (null)[] | null;
    Description: string;
    UpdatedBy?: null;
    CreatedBy: CreatedBy;
    Associate?: null;
    Business: BusinessOrCategoryOrTicketPriorityOrCustomerLanguage;
    Category: BusinessOrCategoryOrTicketPriorityOrCustomerLanguage;
    Country: Country;
    Persons?: (null)[] | null;
    NoMailing: boolean;
    Kananame: string;
    Xstop: boolean;
    ActiveInterests: number;
    GroupId: number;
    ActiveStatusMonitorId: number;
    SupportAssociate?: null;
    TicketPriority: BusinessOrCategoryOrTicketPriorityOrCustomerLanguage;
    CustomerLanguage: BusinessOrCategoryOrTicketPriorityOrCustomerLanguage;
    Deleted: number;
    DbiAgentId: number;
    DbiLastSyncronized: string;
    DbiKey: string;
    DbiLastModified: string;
    SupportPerson?: null;
    Address: Address;
    Source: number;
    ActiveErpLinks: number;
    UserDefinedFields: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    ExtraFields: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
  }
  export interface FieldRightOrTableRight {
    Mask: string;
    Reason: string;
  }
  export interface FieldProperties {
    ContactId: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Name: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Department: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    OrgNr: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Number1: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Number2: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    UpdatedDate: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    CreatedDate: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Kananame: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    GroupId: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Deleted: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    DbiAgentId: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    DbiLastSyncronized: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    DbiKey: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    DbiLastModified: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Source: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    ActiveErpLinks: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Interests: InterestsOrPersonsOrAddress;
    Description: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    UpdatedBy: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    CreatedBy: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Associate: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Business: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Category: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Country: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Persons: InterestsOrPersonsOrAddress;
    NoMailing: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Xstop: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    ActiveInterests: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    ActiveStatusMonitorId: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    SupportAssociate: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    TicketPriority: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    CustomerLanguage: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    SupportPerson: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Address: InterestsOrPersonsOrAddress;
    Emails: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Urls: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Phones: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
    Faxes: ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes;
  }
  export interface ContactIdOrNameOrDepartmentOrOrgNrOrNumber1OrNumber2OrUpdatedDateOrCreatedDateOrKananameOrGroupIdOrDeletedOrDbiAgentIdOrDbiLastSyncronizedOrDbiKeyOrDbiLastModifiedOrSourceOrActiveErpLinksOrDescriptionOrUpdatedByOrCreatedByOrAssociateOrBusinessOrCategoryOrCountryOrNoMailingOrXstopOrActiveInterestsOrActiveStatusMonitorIdOrSupportAssociateOrTicketPriorityOrCustomerLanguageOrSupportPersonOrEmailsOrUrlsOrPhonesOrFaxes {
    FieldRight: FieldRightOrTableRight;
    FieldType: string;
    FieldLength: number;
  }
  export interface InterestsOrPersonsOrAddress {
    FieldRight: FieldRightOrTableRight;
    FieldType?: null;
    FieldLength: number;
  }
  export interface EmailsEntityOrUrlsEntityOrPhonesEntity {
    TableRight?: null;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    Value: string;
    StrippedValue: string;
    Description: string;
  }
  export interface FieldPropertiesOrUserDefinedFieldsOrExtraFields {
  }
  export interface InterestsEntity {
    TableRight?: null;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    Id: number;
    Name: string;
    ToolTip: string;
    Deleted: boolean;
    Rank: number;
    Type: string;
    ColorBlock: number;
    IconHint: string;
    Selected: boolean;
    LastChanged: string;
    ChildItems?: (null)[] | null;
    ExtraInfo: string;
    StyleHint: string;
    Hidden: boolean;
    FullName?: null;
  }
  export interface CreatedBy {
    TableRight: FieldRightOrTableRight;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    AssociateId: number;
    Name: string;
    PersonId: number;
    Rank: number;
    Tooltip: string;
    Type: string;
    GroupIdx: number;
    FullName: string;
    FormalName: string;
    Deleted: boolean;
    EjUserId: number;
  }
  export interface BusinessOrCategoryOrTicketPriorityOrCustomerLanguage {
    TableRight?: null;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    Id: number;
    Value: string;
    Tooltip: string;
  }
  export interface Country {
    TableRight?: null;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    CountryId: number;
    Name: string;
    CurrencyId: number;
    EnglishName: string;
    TwoLetterISOCountry: string;
    ThreeLetterISOCountry: string;
    ImageDescription?: null;
    OrgNrText: string;
    InterAreaPrefix: string;
    DialInPrefix: string;
    ZipPrefix: string;
    DomainName: string;
    AddressLayoutId: number;
    DomesticAddressLayoutId: number;
    ForeignAddressLayoutId: number;
    Rank: number;
    Tooltip: string;
    Deleted: boolean;
  }
  export interface Address {
    TableRight?: null;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    Wgs84Latitude: number;
    Wgs84Longitude: number;
    LocalizedAddress?: ((EntityOrLocalizedAddressEntityEntity)[] | null)[] | null;
  }
  export interface EntityOrLocalizedAddressEntityEntity {
    TableRight?: null;
    FieldProperties: FieldPropertiesOrUserDefinedFieldsOrExtraFields;
    Name: string;
    Value: string;
    Tooltip: string;
    Label: string;
    ValueLength: number;
    AddressType: string;
  }
